config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :users, only: %i[new create index]

  resources :listings do
    resources :reservations, only: %i[index new create show]
  end

  resources :reservations, only: [] do
    member do
      get :approve, :reject
    end
  end

  # resources :reservations, only: %i[index]

  resources :wishlists, only: %i[new create destroy] do
    resources :bookmarks, only: %i[create destroy]
  end

  get "hosting", to: "pages#hosting"
  get "hosting/upcoming", to: "pages#upcoming"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :wishlist, dependent: :destroy
  belongs_to :listing, dependent: :destroy
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :reservations
  has_many :bookmarks
  has_many_attached :images

  validates :name, presence: true
  validates :location, presence: true
  validates :details, presence: true
  validates :price, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # before_action :authenticate_user!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :wishlists
  has_many :listings, dependent: :destroy
  has_many :bookmarks, through: :listings
  has_many :reservations

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :phone_number, presence: true, uniqueness: true
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :bookmarks

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :phone_number])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[show]

  def index
    @listings = Listing.all
  end

  def new
    @listing = Listing.new(params[:id])
    @listing.user = current_user
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      redirect_to listings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:name, :location, :details, :price, images: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @listings = Listing.all
  end

  def hosting
    @user = current_user
    # @reservations = Reservation.joins(:listing).where('listings.user_id = ?', current_user.id)
    @reservations = Reservation.joins(:listing).where('listings.user_id = ? AND reservations.status IS NULL', @user.id)
  end

  def upcoming
    @user = current_user
    @reservations = Reservation.joins(:listing).where('listings.user_id = ? AND reservations.status IS TRUE', @user.id)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[show approve reject]

  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_parms)
    @reservation.user = current_user
    if @reservation.save
      redirect_to reservations_path
    else
      render 'listings/show', status: :unprocessable_entity
    end
  end

  def show
    @reservations = listing.reservations
  end

  def approve
    @reservation = Reservation.find(params[:id])
    @reservation.status = true
    if @reservation.save
      redirect_to hosting_upcoming_path
    else
      render 'hosting', status: :unprocessable_entity
    end
  end

  def upcoming
    @reservations = Reservation.all.where('reservations.status.where = ?', true)
  end

  def reject
    @reservation = Reservation.find(params[:id])
    @reservation.status = false
    @reservation.save
    redirect_to hosting_path
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to hosting_path, notice: "Reservation deleted successfully."
  end


  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: %i[new destroy]

  def new
  end

  def create
    @wishlist = Wishlist.new(wishlist_params)
    @wishlist.user = current_user
    if @wishlist.save
      redirect_to wishlists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def destroy
  #   @wishlist.destroy
  #     redirect_to wishlists_path
  # end

  private

  def set_wishlist
    @wishlist = Wishlist.new(params[:id])
  end

  def wishlist_params
    params.require(:wishlist).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/listings/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center mb-4">Listings</h1>
  </div>
</div>

<div class="container col-6 border border-dark rounded-pill mb-4">
    <div class="d-flex justify-content-center">
      <div class="p-2"> Display all Listings</div>
            <div class="p-2"> | </div>
      <div class="p-2 flex-grow-2"><%= link_to "Add New Listing", new_listing_path %></div>
            <div class="p-2"> | </div>
      <div class="p-2 flex-grow-2"><%= link_to "View Reservations", hosting_path %></div>
    </div>
</div>

<div class="container justify-content-center d-flex p-4">
  <div class="display-grid">
    <% @listings.each do |listing| %>
      <div class="listings flex-column mx-4 px-2">
        <div style="position: relative">
          <% listing.images.each do |image| %>
            <%= cl_image_tag image.key, style:'object-fit: cover; width: 110%; height: 16vw; border-radius: 12px;'%>
          <% end %>        
        </div>
            <div class="listing-header d-flex align-items-center" style="justify-content: space-between">
              <h2><%= link_to listing.name, listing_path(listing), class: "text-dark text-decoration-none" %></h2>
                <div class="listing-rating">
                  <i class="fa-solid fa-star"></i>
                  <span>3.9</span>
                </div>
            </div>
              <p><%= listing.location %></p>
              <p><%= listing.details %></p>
              <p><b>$<%= listing.price %></b> per night</p>
      </div>
    <% end %>
  </div>
</div>

app/views/listings/new.html.erb
<div class="container">
  <div class="row">
    <h1>New Listing</h1>
      <%= simple_form_for [@listing] do |f| %>
        <%= f.input :name %>
        <%= f.input :location %>
        <%= f.input :details %>
        <%= f.input :price %>
        <%= f.input :images, as: :file, input_html: { multiple: true } %> 
        <%= f.submit "Submit new listing!", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/listings/show.html.erb
<div class="container">
  <%# Header component here %>
  <h1><%= @listing.name %></h1>

  <div class="header-row">
    <p> <i class="fa-solid fa-star"></i> <%= "4.92 · Superhost · " + @listing.location %></p>
    <p>
      <button type="button" class="btn btn-outline-dark">
        <i class="fa-solid fa-share"></i> Share
      </button>

      <button type="button" class="btn btn-outline-dark">
        <i class="fa-regular fa-heart"></i> Save
      </button>
    </p>
  </div>

  <%# Listing Images here %>
  <div class="images--flex p-1">
      <%= cl_image_tag @listing.images[0].key, style:'object-fit: cover;'%>
    <div class="images--flex__inner">
      <%= cl_image_tag @listing.images[0].key, style:'object-fit: cover;'%>
      <%= cl_image_tag @listing.images[0].key, style:'object-fit: cover;'%>
      <%= cl_image_tag @listing.images[0].key, style:'object-fit: cover;'%>
      <%= cl_image_tag @listing.images[0].key, style:'obect-fit: cover;'%>

    </div>
  </div>



  <%# Listing information here %>
  <%# // LEFT COLUMN //  %>
  <div class="row d-flex flex-start">
    <div class="col-md-7">
      <%# Listing Title %>
      <div class="d-flex align-items-center justify-content-between w-100 border-bottom my-3 pb-3">
        <div>
          <h2>Room in Paris hosted by Moinho</h2>
          <p> · 2 guests · 1 bedroom · 1 bed · 1 bathroom</p>
        </div>

        <%= image_tag 'logo.png', class: 'avatar' %>
      </div>

      <%# Listing Details %>
      <div class="d-flex align-items-center justify-content-start pb-3">
        <i class="fa-solid fa-person-shelter"></i>
        <div class="ms-3">
          <strong>Room in a home</strong>
          <p class="mb-0">Your own room in a home, plus access to shared spaces.</p>
        </div>
      </div>

      <div class="d-flex align-items-center justify-content-start pb-3">
        <i class="fa-solid fa-wifi"></i>
        <div class="ms-3">
          <strong>Dedicated workspace</strong>
          <p class="mb-0">A room with wifi that’s well suited for working.</p>
        </div>
      </div>

      <div class="d-flex align-items-center justify-content-start border-bottom my-3 pb-3">
        <i class="fa-solid fa-xmark"></i>
        <div class="ms-3">
          <strong>Free cancellation for 48 hours.</strong>
        </div>
      </div>

      <%# Meet your Host %>
      <div class="d-flex align-items-center justify-content-start border-bottom mb-3">
        <div class="mb-4">
          <h4>Meet your Host</h4>
          <strong>Eduoard</strong>
          <p class="mb-0">I love music (from early to electronic), I love theatre, film, dance, literature. I like to go mountain biking, hiking, and horseback riding when I can. I love animals, but I prefer that they live in the wild. I'm a visual artist, working mostly on participatory projects. I enjoy meeting new people and sharing some moments of my day with guests.</p>
        </div>
      </div>

      <%# About this place %>
      <div class="d-flex align-items-center justify-content-start border-bottom mb-3">
        <div class="mb-4">
          <h4>About this place</h4>
          <p><%= @listing.name %> is a charming spacious double bedroom and ensuite shower room. Located in the <%= @listing.location %> </p>
          <p class="mb-0">The house is Grade II listed building, dated around 1600. It has full of character, with beautiful garden. Recently refurbished space, with charming decor, the room is a perfec...</p>
          <br>
          <a href="#" class="link-dark">Show more</a> <i class="fa-solid fa-chevron-right"></i>
        </div>
      </div>

      <%# Where you'll sleep %>
      <div class="row border-bottom pb-3 mb-3">
        <h4>Where you'll sleep</h4>
        <div class="col-sm-4">
          <div class="card" style="width: 100%;">
            <div class="card-body text-center">
              <i class="fa-solid fa-bed fa-2x"></i>
              <h5 class="card-title mt-3 mb-0">Bedroom 1</h5>
              <p class="card-text">1 king bed</p>
            </div>
          </div>
        </div>


        <div class="col-sm-4">
          <div class="card" style="width: 100%;">
            <div class="card-body text-center">
              <i class="fa-solid fa-bed fa-2x"></i>
              <h5 class="card-title mt-3 mb-0">Bedroom 2</h5>
              <p class="card-text">1 king bed</p>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
          <div class="card" style="width: 100%;">
            <div class="card-body text-center">
              <i class="fa-solid fa-couch fa-2x"></i>
              <h5 class="card-title mt-3 mb-0">Living Room</h5>
              <p class="card-text">1 sofa</p>
            </div>
          </div>
        </div>
      </div>

      <%# List of amenities %>
      <div class="">
        <h4 class="pb-4">What this place offers</h4>
        <div class="row">

          <div class="col">
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><i class="fa-solid fa-person-dots-from-line"></i> Fast wifi – 155 Mbps</li>
              <li class="list-group-item"><i class="fa-solid fa-person-dots-from-line"></i> Free parking on premises</li>
              <li class="list-group-item"><i class="fa-solid fa-person-dots-from-line"></i> Private patio</li>
              <li class="list-group-item"><i class="fa-solid fa-person-dots-from-line"></i> Garden view</li>
              <li class="list-group-item"><i class="fa-solid fa-person-dots-from-line"></i> Kitchen</li>
            </ul>
          </div>

          <div class="col">
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><i class="fa-solid fa-person-dots-from-line"></i> 22" TV with Chromecast</li>
              <li class="list-group-item"><i class="fa-solid fa-person-dots-from-line"></i> Washing machine</li>
              <li class="list-group-item"><i class="fa-solid fa-person-dots-from-line"></i> Dryer</li>
              <li class="list-group-item"><i class="fa-solid fa-person-dots-from-line"></i> Security cameras on property</li>
              <li class="list-group-item"><i class="fa-solid fa-person-dots-from-line"></i> Hair dryer</li>
            </ul>
          </div>
        </div>
        <br><button type="button" class="btn btn-outline-dark btn-block">Show all 48 amenities</button>
        <br>
      </div>

       <%# Where you'll be%>
      <div class="d-flex align-items-center justify-content-start border-top mt-3">
        <div class="mb-4 mt-4">
          <h4>Where you'll be</h4>
          <img src="https://api.mapbox.com/styles/v1/mapbox/outdoors-v11/static/-122.4515,37.7289,11.62,0/306x200?access_token=pk.eyJ1IjoiYW50bGVyc2FuZGxhZGRlciIsImEiOiJjbGozdWk3cnExbHMxM2t0OHlzbHIzanAzIn0.PgGIqib-qcb-ZHKUdFRBXw">
          <p></p>
          <p><strong><%= @listing.location %></strong></p>
          <p>Beautiful village of <%= @listing.name %> is only 10 minutes walk. You can find a good selection of independent shops, coffee shop, tea rooms, pubs and restaurants or simply enjoying scenic walk at your doorstep.</p>
          <p>...</p>
          <a href="#" class="link-dark">Show more</a> <i class="fa-solid fa-chevron-right"></i>
        </div>
      </div>

    </div>


  <%# // RIGHT COLUMN // %>
  <div class="col-md-5">
    <%# Reservation Form here %>
    <div class="col-md-4 position-sticky" style="top: 80px">
      <div class="card px-5 py-5" id="card1">
        <form>
          <div class="form-group">
            <h5><b>$<%= @listing.price %></b>  night</h5>
            <i class="fa-solid fa-star">4.5 . <span class="reviews">80 reviews</span></i>
          </div>

            <div class="reservations-wrapper">
              <div class="pb-4">
                <div class="border rounded-4 border-secondary">
                  <div class="d-flex rounded border-dark border-bottom">
                    <div class="w-50 text-left ps-3 py-3">
                      <div>CHECK-IN</div>
                      <div class="text-secondary">Add date</div>
                    </div>
                    <div class="w-50 text-left ps-3 py-3 border-start border-dark">
                      <div>CHECKOUT</div>
                      <div class="text-secondary">Add date</div>
                    </div>
                  </div>
                  <div class="w-100 text-left ps-3 py-3">
                    <div class="d-flex justify-content-between pe-4">
                      <div>GUESTS</div>
                      <i class="fa-solid fa-chevron-down"></i>
                    </div>
                    <div class="text-secondary">1 guest</div>
                  </div>
                </div>
              </div>
            </div>
             <%= link_to "Reserve", new_listing_reservation_path(@listing), class: "btn btn-flat btn-red" %>
          </form>
            <div class="justify-content-center d-flex pt-4">
              <i class="fa-solid fa-flag pe-4 pt-1"></i>
              <u><p>Report this listing</p></u>
          </div>
        </div>
      </div>
    </div>

    <%# Things to know %>

  <%#  I AM JUST PUTTING THIS LINE HERE TO SAY ITS THE LATEST %>
</div>

<div class="container border-top border-bottom">
  <h4 class="pt-2">Things to know</h4>
  <div class="row">

    <div class="col-sm">
      <strong>House rules</strong>
      <br>Check-in: 2:00 pm – 11:00 pm
      <br>Checkout before 10:00 am
      <br>4 guests maximum
      <br><a href="#" class="link-dark">Show more</a> <i class="fa-solid fa-chevron-right"></i>
    </div>

    <div class="col-sm">
      <strong>Safety & property</strong>
      <br>Carbon monoxide alarm
      <br>Smoke alarm
      <br>Not suitable for infants (under 2 years)
      <br><a href="#" class="link-dark">Show more</a> <i class="fa-solid fa-chevron-right"></i>
    </div>

    <div class="col-sm">
      <strong>Cancellation policy</strong>
      <br>Free cancellation before 10 Aug.
      <br>Review the Host’s full cancellation policy which applies even if you cancel for illness or disruptions caused by COVID-19.
      <br><a href="#" class="link-dark">Show more</a> <i class="fa-solid fa-chevron-right"></i>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<br>
<div class="container">

  <div class="nav black-text d-flex justify-content-center">
    <ul class="nav">

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-solid fa-icons"></i>
        <a class="nav-link active" aria-current="page" href="#">OMG!</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-solid fa-person-shelter"></i>
        <a class="nav-link" href="#">Rooms</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
      <i class="fa-solid fa-umbrella-beach"></i>
      <a class="nav-link" href="#">Beach</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-solid fa-mountain-sun"></i>
        <a class="nav-link" href="#">Amazing views</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-solid fa-campground"></i>
        <a class="nav-link" href="#">Cabins</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-solid fa-tractor"></i>
        <a class="nav-link" href="#">Farms</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
      <i class="fa-solid fa-star"></i>
      <a class="nav-link" href="#">Luxe</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-solid fa-caravan"></i>
        <a class="nav-link" href="#">Camping</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-brands fa-slack"></i>
        <a class="nav-link" href="#">Ryokans</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-solid fa-suitcase"></i>
        <a class="nav-link" href="#">Tiny Homes</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-solid fa-chess-rook"></i>
        <a class="nav-link" href="#">Castles</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-solid fa-hurricane"></i>
        <a class="nav-link" href="#">Tropical</a>
      </li>
    <% end %>

    <%= link_to "#" do %>
      <li class="nav-item d-flex flex-column align-items-center">
        <i class="fa-solid fa-archway"></i>
        <a class="nav-link" href="#">Mansions</a>
      </li>
    <% end %>
    </ul>
  </div>
  <br>
  <br>

  <div class="price-switcher-wrapper">
    <div class="text-dark p-2">Display all prices</div>
    <div class="my-2 px-1 flex-grow-1 border-start text-secondary">Includes all fees, before taxes</div>
    <div class="switch">
      <label class="switch">
      <input type="checkbox">
      <span class="slider round"></span>
      </label>
    </div>
  </div>
  <br>
  <br>

  <div class="display-grid">
    <% @listings.each do |listing| %>
      <div class="mx-2 px-3">
        <div style="position: relative;">
          <i class="fa-regular fa-heart" style="color: #e53ece; position: absolute; right: 20px; top: 20px; font-size: 1.8rem;"></i>
        </div>
        <%= cl_image_tag(listing.images.attached? ? listing.images.first.key : "https://res.cloudinary.com/dulb8hprm/image/upload/r_50/v1687072605/h3lvkbuk8vb9wpwatjc3.jpg", style:'object-fit: cover; width: 100%; height: 18vw; border-radius: 12px;')%>
        <div class="listing-header d-flex align-items-center" style="justify-content: space-between">
            <h2><%= link_to listing.name, listing_path(listing), class: "text-dark text-decoration-none" %></h2>            <div class="listing-rating">
              <i class="fa-solid fa-star"></i>
              <span>3.9</span>
            </div>
        </div>
        <p><%= listing.location %></p>
        <p><%= listing.details %></p>
        <p><b>$<%= listing.price %></b> per night</p>
      </div>
    <% end %>
  </div>
</div>

<button type="button" class="map-btn d-flex align-items-center">Show map&nbsp;&nbsp;<i class="fa-solid fa-map-location-dot"></i></button>

app/views/pages/hosting.html.erb
<div class="container">
  <h1>Welcome, <%= @user.name %></h1>

  <br>

  <div>
    <h2 class="fs-4 text">Your Reservations </h2>
    <br>
    <br>
    <h3><%#= link_to "All reservations", "#", class: "d-flex btn btn-ghost text-dark" %></h3>
  </div>
  <div class="border-bottom">
    <%= link_to "Checking out", "#", class: "btn btn-ghost text-dark" %>
    <%= link_to "Currently hosting", "#", class: "btn btn-ghost text-dark" %>
    <%= link_to "Arriving soon", "#", class: "btn btn-ghost text-dark" %>
    <%= link_to "Upcoming", hosting_upcoming_path, class: "btn btn-ghost text-dark" %>
    <%= link_to "#", class: "btn btn-ghost text-dark" do %>
      Pending (<%= @reservations.length %>)
    <% end %>
  </div>

  <br>

  <div>
    <% if @reservations.length === 0 %>
      <p class="d-flex justify-content-center fw-medium m-5 border-bottom">You have no upcoming reservations.</p>
      <%# <p class="d-flex justify-content-center"> See all reservations</p> %>
    <% else %>
      <%# New style %>
      <div class="container d-flex justify-content-left">
        <div class="d-flex display-grid">
          <% @reservations.each do |reservation| %>
            <div class="reservations flex-column mx-2">
              <div style="position: relative;">
                <div class="reservation-header d-flex align-items-center" style="justify-content: space-between">
                  <h2 class="mb-3"><%= reservation.listing.name %></h2>
                  </div>
                <%= cl_image_tag(reservation.listing.images.first.key, style:'object-fit: cover; width: 18vw; height: 18vw; border-radius: 12px;')%>
                <%#= cl_image_tag(reservation.images.attached? ? reservation.listing.images.first.key : "https://res.cloudinary.com/dulb8hprm/image/upload/r_50/v1687072605/h3lvkbuk8vb9wpwatjc3.jpg", style:'object-fit: cover; width: 18vw; height: 18vw; border-radius: 12px;')%>
                  <p class="mt-3">Booked by: <%= reservation.user.name %></p>
                  <p>Booking from: <%= reservation.start_date %></p>
                  <p>Until: <%= reservation.end_date %></p>
                <%# Accept/ Decline buttons %>
                <div class="d-flex justify-content-evenly me-1">
                  <%= link_to "Accept", approve_reservation_path(reservation), class: "btn btn-gradient bg-success bg-gradient text-light" %>
                  <%#= link_to "Decline", "#", class: "btn btn-gradient bg-danger bg-gradient text-light" %>
                  <%= link_to "Decline", reject_reservation_path(reservation), class: "btn btn-danger bg-gradient text-light" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <div class="d-flex justify-content-center border-top">
    <p>How can we make it easier to manage your reservations? Share your feedback</p>
  </div>



</div>

app/views/reservations/new.html.erb
<div class="container">
  <h1>Reserved!</h1>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom fixed-top">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "imgbin_airbnb-logo-png.png"%>
    <% end %>

    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>

    <%= render "shared/nav/searchstate"%>
    <%= render "shared/nav/dropdown" %>
  </div>
</div>
<div style="padding: 2.5rem;"></div>

app/views/wishlists/new.html.erb
<div class="container">
  <div class="row">
    <h1>Wishlists</h1>
    <%= simple_form_for [@wishlist] do |f| %>
      <%= f.input :name %>
      <%= f.submit "Create Wishlist!", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>